version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=W3lkom0!
      - DOCKER_INFLUXDB_INIT_ORG=GrypeScanOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=GrypeScanResults
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - scrapernetwork

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=W3lkom0!
    networks:
      - scrapernetwork

networks:
  scrapernetwork:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:
