trigger:
- main

name: $(date:yyyy.MM.dd)$(rev:.r)
pool:
    vmImage: 'ubuntu-latest'

stages:
  - stage: build
    displayName: Build and publish image
    jobs:
      - template: build.yml
        parameters:
          imageName: 'vulnerabilityaggregatorcontainerjob'
          containerRegistry: '[REGISTRY_NAME]'
          entrypointFolder: 'src/VulnerabilityAggregatorJob'
          resourceGroup: '[RESOURCEGROUP_NAME]'
          azureSubscription: '[AZURESUBSCRIPTION_NAME]'

  - stage: deploy_dev
    displayName: Deploy to dev azure
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn: build
    jobs:
    - deployment: Deploy_dev
      displayName: Deploy dev
      environment: [ENVIROMENT_NAME]
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: 'self'
            - task: AzureResourceManagerTemplateDeployment@3
              name: deploy_container_app
              inputs:
                deploymentScope: 'Resource Group'
                resourceGroupName: '[RESOURCEGROUP_NAME]'
                azureResourceManagerConnection: "[RESOURCMANAGERCONNECTION_NAME]"
                location: "[AUZRE_LOCATION_NAME]"
                templateLocation: 'Linked artifact'
                csmFile: 'deploy/containerapp.bicep'
                csmParametersFile: "deploy/params.dev.json"
                overrideParameters: '-buildNr $(Build.BuildNumber)'
                deploymentMode: 'Incremental'
