parameters:
- name: imageName
  type: string
- name: containerRegistry
  type: string
- name: entrypointFolder
  type: string
- name: resourceGroup
  type: string
- name: azureSubscription
  type: string
- name: scProjectKey
  type: string
- name: scProjectName
  type: string

########################################
jobs:
- job: Build
  displayName: 'Build and publish'
  steps:
  - checkout: self
    fetchDepth: 10
    fetchTags: false

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Publish build'
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      workingDirectory: ${{ parameters.entrypointFolder }}
      projects: ${{ parameters.entrypointFolder }}/*.csproj
      arguments: '--output out --no-restore /p:Version="$(Build.BuildNumber)" /p:InformationalVersion="$(Build.BuildNumber)-$(Build.SourceVersion)"'

  - task: AzureCLI@2
    displayName: 'ACR container build'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      workingDirectory: ${{ parameters.entrypointFolder }}
      inlineScript: 'az acr build --registry ${{ parameters.containerRegistry }} --resource-group ${{ parameters.resourceGroup }} --image ${{ parameters.imageName }}:$(Build.BuildNumber) -t ${{ parameters.imageName }}:latest .'

  - publish: $(Build.SourcesDirectory)/deploy
    displayName: 'Publish deploy dir'
    artifact: deploy